### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by vpavlin** [containers-tools/cct#2]
Reading through Wiki and `dummy.yaml` I see there is term environment mentioned many times. From what I understood it only applies to environment defined by that yaml file, correct? Do you expect users to be able to override `environment` defined in yaml config by real environment variables - as they are basically the only (or at least easiest) way how to pass config options to a container.

My question relates to Nulecule integration - Nulecule spec defines `params` which are passed to artifact for the given provider. We could use `dummy.yaml` as artifact, but I expect it to live inside an image. How is then the user expected to modify it on runtime? Or is he expected to mount it in the container - that would be a bit problematic in kubernetes or OSv3 environment.

**Comment by rwngwn** [comment]
For the first part yes. There will be possibility of using real environment in yaml file. But I'm now thinking of correct way to do it. Because I don't want host environment to silently override yaml ones. Because it will be hard for modules to unset. So I'm thinking of doing stuff like that you can reference variable in a form like:

``` yaml
...
   environment:
     foo: {env.FOO}
   dumy:
      dump: {env.ENVIRON2_NAME} {env.ENVIRON3_NAME}
```

But I dont get second part of question clearly. I will look closer at nulecule and will answer it later.

**Comment by goldmann** [comment]
@vpavlin I split the talk about runtime configuration to #5.

**Comment by rwngwn** [comment]
@vpavlin I've just implement support for environment variables and it works like that https://github.com/containers-tools/cct/wiki/Environment-variables
basicaly you can use any variable from YAML or environment just by specifying its name prefixed with $. 
I hope its sufficient.

**Comment by vpavlin** [comment]
@l-d-j Could you please add an example to your wiki post?

**Comment by rwngwn** [comment]
env was completely reworked
